### ISSUE TITLE
Installation of Emulators does not work; Exit status 1

### ISSUE THREAD

**Issue by HenryKleinschmidt** [mateussouzaweb/nicedeck#2]
The installation stops with "Exit status 1" when trying to install any emulator from the list.

Is there a log file somewhere to see whats happening?
![image](https://github.com/user-attachments/assets/9163cdca-6c20-42ab-827a-cf3ccf2535ce)
![image](https://github.com/user-attachments/assets/d46106b9-a412-4073-9814-ad49f18b5805)

**Comment by mateussouzaweb** [comment]
@HenryKleinschmidt this seems to be an issue with the flatpak command. I just released a new version (0.0.24) that improves the error message, can you try again with this new version?

PS: Just run the command to install NiceDeck again and the installation process will download the latest version.

**Comment by HenryKleinschmidt** [comment]
Sorry for not replying sooner.
When I try to install the new NiceDeck version I get an Gtk-Message error. I think there is a dependency missing. 
![image](https://github.com/user-attachments/assets/395f6728-99c9-4d69-bfe0-4a39beb9ed29)

**Comment by mateussouzaweb** [comment]
That is strange, but I think it is a temporary error generated by the browser. Try to open the app from the mentioned path in the terminal:

./home/deck/Applications/NiceDeck

You can also run it with double click from the Dolphin file browser.

**Comment by HenryKleinschmidt** [comment]
Weird a reboot solved the issue 😄
But I still can't install the emulators. 
![image](https://github.com/user-attachments/assets/60cccc73-9b69-4496-9677-86594f8b73c4)

**Comment by mateussouzaweb** [comment]
@HenryKleinschmidt now I got it! You probably installed EmuDeck and it added a secondary flathub source...
At any case, I just released a new version (0.0.25) and you should be able to install any program with this newer version!

**Comment by HenryKleinschmidt** [comment]
Weird, I did indeed have EmuDeck installed a while ago but I removed it using the official uninstaller. 

But version 0.0.25 did fix the issue! Thank you.
